esphome:
  name: standing-desk-example
  platform: ESP8266
  board: d1_mini

packages:
  standing_desk: github://marcohald/esphome-standing-desk/configs/template.yaml

substitutions:
  standing_desk_uart_rx_pin: 16
  standing_desk_up_pin: D7
  standing_desk_down_pin: D8
  standing_desk_variant: "autonomous"
  standing_desk_min_height: "25.2"
  standing_desk_max_height: "50.8"


  # Optional (defaults shown)
  desk_height_name: "Desk Height"
  target_desk_height_name: "Target Desk Height"
  standing_desk_height_units: "in"